version: '3'

services:
  app:
    build:
      context: .
    ports:
      - 8000:8080
    volumes:
      - ./app:/app
    command: python3 manage.py runserver 0.0.0.0:8080
# ＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
# volumeに関して
# volumesはディレクトリーの同期
# volumeを設定することで、コンテナの中で作ったファイルはローカルにも共有されて消えなく
# なるし、自分のパソコン上にあるpythonファイルを./appに置くことで、コンテナ側でも
# 使うことができる

# ＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

# ＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
# portsに関して
# ブラウザーでlocalhost8000ききたら、コンテナの8080番ポートに繋いでねという意味
# ports:
#   - 8000:8080

# つまり、ホスト側のポート番号:コンテナ側のポート番号

# また、コンテナ内では、command: python3 manage.py runserver 0.0.0.0:8080で
# サーバーを動かしているので、サーバーが起動している状態になる

# ＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

# ＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
# dockerのコンテナの中に入るまでのコマンド

# コンテナを立ち上げる
# docker-compose up -d

# 以下のコマンドで、どのコンテナ名がわかる 今回であればapp
# docker-compose ps --service

# コンテナの中に入る。exec コンテナ名を入れる
# docker-compose exec app /bin/sh
# ＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

# ＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
# docker-compose.ymlの変更を反映させる
# foregroundで起動
# docker-compose up

# backgroundで起動
# docker-compose up -d
# ＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

# ＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
# Dockerfile or ビルド処理の変更を反映させる
# foregroundで起動
# docker-compose up --build

# backgroundで起動
# docker-compose up -d --build
# ＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝

# ＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
# コンテナのmigrationのコマンド
# docker-compose run app python manage.py showmigrations
# ＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
