# Generated by Django 2.2.2 on 2020-05-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='uuid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='uuid',
            new_name='id',
        ),
    ]
