# Generated by Django 2.2.2 on 2020-06-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=32, verbose_name='ニックネーム'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yorozu_id',
            field=models.CharField(default='', max_length=32, primary_key=True, serialize=False, verbose_name='YOROZU\x08 ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yorozuya_name',
            field=models.CharField(default='', max_length=32, verbose_name='万屋の名前'),
        ),
    ]
