# Generated by Django 2.2.2 on 2020-09-20 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='app_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='yorozu.Profile', verbose_name='アプリID'),
        ),
    ]
