# Generated by Django 2.2.2 on 2020-05-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ログイン状態'),
        ),
    ]
