# Generated by Django 2.2.2 on 2020-06-12 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_plan',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='contract_plan', to='yorozu.Plan', verbose_name='契約をしたプラン'),
        ),
    ]
