# Generated by Django 2.2.2 on 2020-05-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isRead',
            field=models.BooleanField(default=False, verbose_name='既読判定'),
        ),
    ]
