# Generated by Django 2.2.2 on 2020-06-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0002_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='isApproval',
            field=models.BooleanField(default=False, verbose_name='リクエストの承認状態'),
        ),
    ]
