# Generated by Django 2.2.2 on 2020-05-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0002_message_isread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_content',
            field=models.TextField(max_length=600, verbose_name='メッセージ内容'),
        ),
    ]
