# Generated by Django 2.2.2 on 2020-06-13 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0002_contract_contract_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='isApproval',
            new_name='is_approval',
        ),
    ]
