# Generated by Django 2.2.2 on 2020-07-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0002_auto_20200627_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.AddField(
            model_name='message',
            name='unread',
            field=models.BooleanField(default=True, verbose_name='既読判定'),
        ),
    ]
