# Generated by Django 2.2.2 on 2020-06-06 16:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0003_request_isapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isApproval', models.BooleanField(default=False, verbose_name='契約の承認状態')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日')),
                ('receiver_yorozu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_receiver', to='yorozu.Profile', verbose_name='リクエスト受信者')),
                ('sender_yorozu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_sender', to='yorozu.Profile', verbose_name='リクエスト送信者')),
            ],
            options={
                'verbose_name_plural': '契約',
            },
        ),
    ]
