# Generated by Django 2.2.2 on 2020-06-20 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0003_auto_20200613_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='yorozu_main_image',
            new_name='plan_thumbnail_image',
        ),
    ]
