# Generated by Django 2.2.2 on 2020-07-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0003_auto_20200706_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='plan_thumbnail_image',
        ),
        migrations.AddField(
            model_name='profile',
            name='yorozuya_thumbnail_image',
            field=models.ImageField(default='', upload_to='', verbose_name='よろず屋サムネ画像(トップページの画像)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='unread',
            field=models.BooleanField(default=True, verbose_name='未読判定(未読ならTrue)'),
        ),
    ]
