# Generated by Django 2.2.2 on 2020-06-25 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0004_auto_20200620_1844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
