# Generated by Django 2.2.2 on 2020-07-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0004_auto_20200706_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name_plural': 'お支払い'},
        ),
    ]
