# Generated by Django 2.2.2 on 2020-06-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0004_contract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name_plural': '契約(本契約)'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name_plural': 'リクエスト(仮契約)'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='isRead',
            new_name='is_read',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='isApproval',
            new_name='is_approval',
        ),
    ]
