# Generated by Django 2.2.2 on 2020-06-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0005_delete_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name_plural': '契約'},
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_content',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_score',
        ),
        migrations.AddField(
            model_name='review',
            name='is_negative_score',
            field=models.BooleanField(default=False, verbose_name='ネガティブ得点'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_positive_score',
            field=models.BooleanField(default=False, verbose_name='ポジティブ得点'),
        ),
    ]
