# Generated by Django 2.2.2 on 2020-07-11 06:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0005_auto_20200711_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField(default=0, verbose_name='料金')),
            ],
            options={
                'verbose_name_plural': '支払い',
            },
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name_plural': '契約'},
        ),
    ]
