# Generated by Django 2.2.2 on 2020-07-11 06:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0006_auto_20200711_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='更新日'),
        ),
    ]
