# Generated by Django 2.2.2 on 2020-06-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yorozu', '0006_auto_20200625_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook_account',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram_account',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='review_score',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter_account',
        ),
    ]
